### ISSUE TITLE
Deploy to Cloud button doesn't work

### ISSUE THREAD

**Issue by mikespub** [docker/dockercloud-hello-world#6]
Not sure where else to submit this, but the "Deploy to Cloud" button doesn't seem to work even when specifying a repository, despite what https://docs.docker.com/docker-cloud/apps/deploy-to-cloud-btn/ claims.

The problem seems to be on the cloud.docker.com side, because https://cloud.docker.com/stack/deploy/?repo=https://github.com/docker/dockercloud-quickstart-python (or whatever repo you want) leads to a blank page.

**Comment by fermayo** [comment]
Yes, we are aware of that and working to fix it ASAP. Thanks for the heads up.

**Comment by auser** [comment]
Any news on this? _bump_

_bump_

**Comment by jekkos** [comment]
+1

**Comment by fermayo** [comment]
This is fixed
